# Generated by Django 2.2.7 on 2019-11-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Product')),
                ('category', models.CharField(choices=[('other', 'Other'), ('food', 'Food'), ('clothes', 'Clothes'), ('households', 'Households')], default='other', max_length=50, verbose_name='Category')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='products_images')),
            ],
        ),
    ]
